In [1]:
import numpy as np

In [2]:
def sliding_windows(tokens, block_size, stride):
    # tokens: 1D np.array of int (length L)
    L = len(tokens)
    if L < block_size:
        return []

    starts = np.arange(0, L - block_size + 1, stride)
    return [tokens[s:s+block_size] for s in starts]

def chunk_windows(tokens, block_size):
    L = len(tokens)
    n = L // block_size
    return [tokens[i*block_size:(i+1)*block_size] for i in range(n)]

In [3]:
L, ctx, stride = 10000, 2048, 256
tokens = np.arange(L)

In [4]:
windows = sliding_windows(tokens, ctx, stride)  # 形如 [ (2048,), (2048,), ... ]

print("=> sliding_windows: [:5]")
for i in range(5):
    print(windows[i])

=> sliding_windows: [:5]
[   0    1    2 ... 2045 2046 2047]
[ 256  257  258 ... 2301 2302 2303]
[ 512  513  514 ... 2557 2558 2559]
[ 768  769  770 ... 2813 2814 2815]
[1024 1025 1026 ... 3069 3070 3071]


In [5]:
windows = chunk_windows(tokens, ctx)

print("=> chunk_windows:")
for i in range(len(windows)):
    print(windows[i])

=> chunk_windows:
[   0    1    2 ... 2045 2046 2047]
[2048 2049 2050 ... 4093 4094 4095]
[4096 4097 4098 ... 6141 6142 6143]
[6144 6145 6146 ... 8189 8190 8191]
